services:
  server:
    build:
      context: ./server
      dockerfile: docker/Dockerfile
    container_name: reactrack-server
    ports:
      - "4000:4000"
      - "3003:3003"
      - "3010:3010"
    volumes:
      - ./server:/app
      - /app/node_modules
    command: npm run dev-server-with-all
    env_file:
      - ./server/.env
    environment:
      - NODE_ENV=development

  client:
    build:
      context: ./client
    container_name: reactrack-client
    ports:
      - "5173:5173"
    volumes:
      - ./client:/app
      - /app/node_modules
    command: npm run dev
    depends_on:
      - server
      - server-csharp
    env_file:
      - ./client/.env.local
    environment:
      VITE_BACKEND_URL: http://localhost:4000
      
  postgres:
    image: postgres:16-alpine
    container_name: reactrack-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: reactrack_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "123"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  server-csharp:
    image: mcr.microsoft.com/dotnet/sdk:8.0
    container_name: reactrack-server-csharp
    working_dir: /src
    ports:
      - "5000:5000"
    volumes:
      - ./server-csharp:/src
    command: /bin/sh -c "dotnet restore ReactRack/ReactRack.csproj && dotnet watch --project ReactRack/ReactRack.csproj run --urls http://0.0.0.0:5000"
    depends_on:
      - postgres
    env_file:
      - ./server/.env
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__Postgres: Host=postgres;Port=5432;Database=reactrack_db;Username=postgres;Password=123

  client-angular:
    image: node:22-alpine
    container_name: reactrack-client-angular
    working_dir: /app
    ports:
      - "4200:4200"
    volumes:
      - ./client-angular:/app
      - /app/node_modules
      - ./client-angular/src/environments/environment.docker.ts:/app/src/environments/environment.ts:ro
    command: >
      /bin/sh -c "npm install && echo 'Começando a aplicação em Angular com Mapeamento de Volume 🚀' && npm start"
    depends_on:
      - server
      - server-csharp

volumes:
  postgres_data: